import json, sys, os
sys.stdout.reconfigure(encoding='utf-8')

BASE = r"C:\Users\svenb\Desktop\loruuh\02 Spanish Generator\CapturCherry"
PERSONS = ["yo","tú","él/ella","nosotros","vosotros","ellos"]
TENSE_ORDER = ["Präsens","Vergangenheit","Zukunft","Konditional"]
VERB_ORDER  = ["ser","estar","tener","haber","ir","hacer","poder","decir","ver","dar","saber","querer","venir","poner","salir"]

DATA = {
"ser": {
  "start": 2948, "name": "Ser – Konjugation", "icon": "🔴",
  "desc": "ser in Präsens, Vergangenheit, Zukunft & Konditional",
  "conj": {
    "Präsens":       ["soy","eres","es","somos","sois","son"],
    "Vergangenheit": ["fui","fuiste","fue","fuimos","fuisteis","fueron"],
    "Zukunft":       ["seré","serás","será","seremos","seréis","serán"],
    "Konditional":   ["sería","serías","sería","seríamos","seríais","serían"],
  },
  "de": {
    "Präsens":       ["ich bin","du bist","er/sie ist","wir sind","ihr seid","sie sind"],
    "Vergangenheit": ["ich war","du warst","er/sie war","wir waren","ihr wart","sie waren"],
    "Zukunft":       ["ich werde sein","du wirst sein","er/sie wird sein","wir werden sein","ihr werdet sein","sie werden sein"],
    "Konditional":   ["ich wäre","du wärst","er/sie wäre","wir wären","ihr wärt","sie wären"],
  },
  "ex": {
    ("Präsens",0): ("Soy estudiante.","Ich bin Student."),
    ("Präsens",1): ("¿Eres de España?","Bist du aus Spanien?"),
    ("Präsens",2): ("Ella es muy simpática.","Sie ist sehr nett."),
    ("Präsens",3): ("Somos cuatro hermanos.","Wir sind vier Geschwister."),
    ("Präsens",4): ("¿Sois de Madrid?","Seid ihr aus Madrid?"),
    ("Präsens",5): ("Son las diez de la noche.","Es ist zehn Uhr abends."),
    ("Vergangenheit",0): ("Ayer fui al médico.","Gestern war ich beim Arzt."),
    ("Vergangenheit",1): ("¿Fuiste tú quien llamó?","Warst du derjenige, der angerufen hat?"),
    ("Vergangenheit",2): ("Fue una gran sorpresa.","Es war eine große Überraschung."),
    ("Vergangenheit",3): ("Fuimos los primeros en llegar.","Wir waren die Ersten, die ankamen."),
    ("Vergangenheit",4): ("¿Fuisteis al concierto ayer?","Wart ihr gestern beim Konzert?"),
    ("Vergangenheit",5): ("Fueron muy amables con nosotros.","Sie waren sehr freundlich zu uns."),
    ("Zukunft",0): ("Seré médico algún día.","Eines Tages werde ich Arzt sein."),
    ("Zukunft",1): ("Serás un gran músico.","Du wirst ein großer Musiker sein."),
    ("Zukunft",2): ("La reunión será a las cinco.","Das Treffen wird um fünf sein."),
    ("Zukunft",3): ("Seremos felices juntos.","Wir werden glücklich zusammen sein."),
    ("Zukunft",4): ("Seréis los mejores del equipo.","Ihr werdet die Besten des Teams sein."),
    ("Zukunft",5): ("Las clases serán por la mañana.","Der Unterricht wird morgens sein."),
    ("Konditional",0): ("Sería mejor esperar un poco.","Es wäre besser, etwas zu warten."),
    ("Konditional",1): ("Serías un buen maestro.","Du wärst ein guter Lehrer."),
    ("Konditional",2): ("Sería perfecto para ese puesto.","Er/sie wäre perfekt für die Stelle."),
    ("Konditional",3): ("Seríamos más felices allí.","Wir wären dort glücklicher."),
    ("Konditional",4): ("Seríais buenos en ese trabajo.","Ihr wärt gut in dieser Arbeit."),
    ("Konditional",5): ("Serían las mejores opciones.","Das wären die besten Möglichkeiten."),
  },
},
"estar": {
  "start": 2972, "name": "Estar – Konjugation", "icon": "🟡",
  "desc": "estar in Präsens, Vergangenheit, Zukunft & Konditional",
  "conj": {
    "Präsens":       ["estoy","estás","está","estamos","estáis","están"],
    "Vergangenheit": ["estuve","estuviste","estuvo","estuvimos","estuvisteis","estuvieron"],
    "Zukunft":       ["estaré","estarás","estará","estaremos","estaréis","estarán"],
    "Konditional":   ["estaría","estarías","estaría","estaríamos","estaríais","estarían"],
  },
  "de": {
    "Präsens":       ["ich bin","du bist","er/sie ist","wir sind","ihr seid","sie sind"],
    "Vergangenheit": ["ich war","du warst","er/sie war","wir waren","ihr wart","sie waren"],
    "Zukunft":       ["ich werde sein","du wirst sein","er/sie wird sein","wir werden sein","ihr werdet sein","sie werden sein"],
    "Konditional":   ["ich wäre","du wärst","er/sie wäre","wir wären","ihr wärt","sie wären"],
  },
  "ex": {
    ("Präsens",0): ("Estoy en casa ahora.","Ich bin jetzt zu Hause."),
    ("Präsens",1): ("¿Cómo estás hoy?","Wie geht es dir heute?"),
    ("Präsens",2): ("La puerta está abierta.","Die Tür ist offen."),
    ("Präsens",3): ("Estamos listos para salir.","Wir sind bereit loszugehen."),
    ("Präsens",4): ("¿Estáis cansados?","Seid ihr müde?"),
    ("Präsens",5): ("Los niños están durmiendo.","Die Kinder schlafen gerade."),
    ("Vergangenheit",0): ("Estuve en Madrid el año pasado.","Letztes Jahr war ich in Madrid."),
    ("Vergangenheit",1): ("¿Estuviste en la fiesta anoche?","Warst du gestern Abend auf der Party?"),
    ("Vergangenheit",2): ("Estuvo enfermo toda la semana.","Er/sie war die ganze Woche krank."),
    ("Vergangenheit",3): ("Estuvimos esperando dos horas.","Wir haben zwei Stunden gewartet."),
    ("Vergangenheit",4): ("¿Estuvisteis en casa todo el día?","Wart ihr den ganzen Tag zu Hause?"),
    ("Vergangenheit",5): ("Estuvieron de viaje tres semanas.","Sie waren drei Wochen auf Reisen."),
    ("Zukunft",0): ("Estaré en casa a las seis.","Ich werde um sechs zu Hause sein."),
    ("Zukunft",1): ("Estarás bien muy pronto.","Du wirst sehr bald wieder gesund sein."),
    ("Zukunft",2): ("La tienda estará cerrada mañana.","Der Laden wird morgen geschlossen sein."),
    ("Zukunft",3): ("Estaremos listos para el lunes.","Wir werden bis Montag fertig sein."),
    ("Zukunft",4): ("Estaréis orgullosos del resultado.","Ihr werdet stolz auf das Ergebnis sein."),
    ("Zukunft",5): ("Estarán de vacaciones la semana que viene.","Sie werden nächste Woche im Urlaub sein."),
    ("Konditional",0): ("Estaría mejor en casa hoy.","Ich wäre heute zu Hause besser aufgehoben."),
    ("Konditional",1): ("Estarías más cómodo en el sofá.","Du wärst auf dem Sofa bequemer."),
    ("Konditional",2): ("Estaría bien tomar un descanso.","Es wäre gut, eine Pause zu machen."),
    ("Konditional",3): ("Estaríamos allí a tiempo.","Wir wären rechtzeitig dort."),
    ("Konditional",4): ("Estaríais más tranquilos en el campo.","Ihr wärt auf dem Land ruhiger."),
    ("Konditional",5): ("Estarían encantados de ayudarte.","Sie wären begeistert, dir zu helfen."),
  },
},
"tener": {
  "start": 2996, "name": "Tener – Konjugation", "icon": "💪",
  "desc": "tener in Präsens, Vergangenheit, Zukunft & Konditional",
  "conj": {
    "Präsens":       ["tengo","tienes","tiene","tenemos","tenéis","tienen"],
    "Vergangenheit": ["tuve","tuviste","tuvo","tuvimos","tuvisteis","tuvieron"],
    "Zukunft":       ["tendré","tendrás","tendrá","tendremos","tendréis","tendrán"],
    "Konditional":   ["tendría","tendrías","tendría","tendríamos","tendríais","tendrían"],
  },
  "de": {
    "Präsens":       ["ich habe","du hast","er/sie hat","wir haben","ihr habt","sie haben"],
    "Vergangenheit": ["ich hatte","du hattest","er/sie hatte","wir hatten","ihr hattet","sie hatten"],
    "Zukunft":       ["ich werde haben","du wirst haben","er/sie wird haben","wir werden haben","ihr werdet haben","sie werden haben"],
    "Konditional":   ["ich hätte","du hättest","er/sie hätte","wir hätten","ihr hättet","sie hätten"],
  },
  "ex": {
    ("Präsens",0): ("Tengo mucha hambre.","Ich habe großen Hunger."),
    ("Präsens",1): ("¿Tienes un momento?","Hast du einen Moment?"),
    ("Präsens",2): ("Tiene veinte años.","Er/sie ist zwanzig Jahre alt."),
    ("Präsens",3): ("Tenemos una reunión importante.","Wir haben ein wichtiges Meeting."),
    ("Präsens",4): ("¿Tenéis suficiente dinero?","Habt ihr genug Geld?"),
    ("Präsens",5): ("Tienen razón en eso.","Sie haben damit recht."),
    ("Vergangenheit",0): ("Tuve un día muy difícil.","Ich hatte einen sehr schwierigen Tag."),
    ("Vergangenheit",1): ("¿Tuviste suerte en el examen?","Hattest du Glück bei der Prüfung?"),
    ("Vergangenheit",2): ("Tuvo que esperar mucho tiempo.","Er/sie musste sehr lange warten."),
    ("Vergangenheit",3): ("Tuvimos muchos problemas.","Wir hatten viele Probleme."),
    ("Vergangenheit",4): ("¿Tuvisteis tiempo de comer?","Hattet ihr Zeit zu essen?"),
    ("Vergangenheit",5): ("Tuvieron que cancelar el viaje.","Sie mussten die Reise absagen."),
    ("Zukunft",0): ("Tendré más tiempo la semana que viene.","Nächste Woche werde ich mehr Zeit haben."),
    ("Zukunft",1): ("Tendrás que estudiar más.","Du wirst mehr lernen müssen."),
    ("Zukunft",2): ("Tendrá razón, supongo.","Er/sie wird wohl recht haben."),
    ("Zukunft",3): ("Tendremos una reunión el lunes.","Wir werden am Montag ein Meeting haben."),
    ("Zukunft",4): ("Tendréis mucha suerte.","Ihr werdet viel Glück haben."),
    ("Zukunft",5): ("Tendrán que decidir pronto.","Sie werden bald entscheiden müssen."),
    ("Konditional",0): ("Tendría más cuidado la próxima vez.","Ich würde beim nächsten Mal vorsichtiger sein."),
    ("Konditional",1): ("Tendrías más éxito con práctica.","Du hättest mit Übung mehr Erfolg."),
    ("Konditional",2): ("Tendría paciencia en tu lugar.","Er/sie hätte an deiner Stelle Geduld."),
    ("Konditional",3): ("Tendríamos más tiempo así.","Wir hätten so mehr Zeit."),
    ("Konditional",4): ("Tendríais que decidirlo vosotros.","Ihr hättet das selbst entscheiden müssen."),
    ("Konditional",5): ("Tendrían que hablar con el jefe.","Sie hätten mit dem Chef sprechen müssen."),
  },
},
"haber": {
  "start": 3020, "name": "Haber – Konjugation", "icon": "✅",
  "desc": "haber (Hilfsverb) in 4 Zeiten + hay (es gibt)",
  "conj": {
    "Präsens":       ["he","has","ha","hemos","habéis","han"],
    "Vergangenheit": ["hube","hubiste","hubo","hubimos","hubisteis","hubieron"],
    "Zukunft":       ["habré","habrás","habrá","habremos","habréis","habrán"],
    "Konditional":   ["habría","habrías","habría","habríamos","habríais","habrían"],
  },
  "de": {
    "Präsens":       ["ich habe","du hast","er/sie hat","wir haben","ihr habt","sie haben"],
    "Vergangenheit": ["ich hatte (Vorvergangenheit)","du hattest (Vorvergangenheit)","er/sie hatte (Vorvergangenheit)","wir hatten (Vorvergangenheit)","ihr hattet (Vorvergangenheit)","sie hatten (Vorvergangenheit)"],
    "Zukunft":       ["ich werde haben","du wirst haben","er/sie wird haben","wir werden haben","ihr werdet haben","sie werden haben"],
    "Konditional":   ["ich würde haben","du würdest haben","er/sie würde haben","wir würden haben","ihr würdet haben","sie würden haben"],
  },
  "ex": {
    ("Präsens",0): ("He comido demasiado.","Ich habe zu viel gegessen."),
    ("Präsens",1): ("¿Has visto esa película?","Hast du diesen Film gesehen?"),
    ("Präsens",2): ("Ella ha llegado tarde.","Sie ist spät angekommen."),
    ("Präsens",3): ("Hemos terminado el proyecto.","Wir haben das Projekt beendet."),
    ("Präsens",4): ("¿Habéis reservado mesa?","Habt ihr einen Tisch reserviert?"),
    ("Präsens",5): ("Han salido a las ocho.","Sie sind um acht ausgegangen."),
    ("Vergangenheit",0): ("Cuando hube terminado, salí.","Als ich fertig war, ging ich."),
    ("Vergangenheit",1): ("Cuando hubiste llegado, llamaste.","Als du angekommen warst, riefst du an."),
    ("Vergangenheit",2): ("Cuando hubo comido, se marchó.","Als er/sie gegessen hatte, ging er/sie."),
    ("Vergangenheit",3): ("Cuando hubimos salido, cerró.","Als wir gegangen waren, schloss er."),
    ("Vergangenheit",4): ("Después de que hubisteis entrado, empezó.","Nachdem ihr hineingegangen wart, begann es."),
    ("Vergangenheit",5): ("Cuando hubieron llegado, empezamos.","Als sie angekommen waren, begannen wir."),
    ("Zukunft",0): ("Para mañana habré terminado el informe.","Bis morgen werde ich den Bericht fertig haben."),
    ("Zukunft",1): ("Habrás oído la noticia para entonces.","Du wirst die Neuigkeit bis dahin gehört haben."),
    ("Zukunft",2): ("Para el viernes habrá llegado.","Bis Freitag wird er/sie angekommen sein."),
    ("Zukunft",3): ("Para el lunes habremos terminado.","Bis Montag werden wir fertig sein."),
    ("Zukunft",4): ("Para la cena habréis vuelto.","Bis zum Abendessen werdet ihr zurück sein."),
    ("Zukunft",5): ("Ya habrán llegado a casa.","Sie werden schon zu Hause angekommen sein."),
    ("Konditional",0): ("Habría venido antes si hubiera sabido.","Ich wäre früher gekommen, wenn ich es gewusst hätte."),
    ("Konditional",1): ("Habrías ganado si hubieras jugado.","Du hättest gewonnen, wenn du gespielt hättest."),
    ("Konditional",2): ("Habría sido mejor esperar.","Es wäre besser gewesen zu warten."),
    ("Konditional",3): ("Habríamos llegado antes sin el tráfico.","Wir wären ohne den Stau früher angekommen."),
    ("Konditional",4): ("Habríais disfrutado la película.","Ihr hättet den Film genossen."),
    ("Konditional",5): ("Ya habrían terminado sin los problemas.","Sie wären ohne die Probleme schon fertig gewesen."),
  },
  "extra": [
    {"spanish":"hay","german":"es gibt","sentence_es":"Hay un banco en la esquina.","sentence_de":"Es gibt eine Bank an der Ecke.","note":"haber – Impersonal – hay (es gibt)"},
  ],
},
"ir": {
  "start": 3045, "name": "Ir – Konjugation", "icon": "🚶",
  "desc": "ir in Präsens, Vergangenheit, Zukunft & Konditional",
  "conj": {
    "Präsens":       ["voy","vas","va","vamos","vais","van"],
    "Vergangenheit": ["fui","fuiste","fue","fuimos","fuisteis","fueron"],
    "Zukunft":       ["iré","irás","irá","iremos","iréis","irán"],
    "Konditional":   ["iría","irías","iría","iríamos","iríais","irían"],
  },
  "de": {
    "Präsens":       ["ich gehe","du gehst","er/sie geht","wir gehen","ihr geht","sie gehen"],
    "Vergangenheit": ["ich ging","du gingst","er/sie ging","wir gingen","ihr gingt","sie gingen"],
    "Zukunft":       ["ich werde gehen","du wirst gehen","er/sie wird gehen","wir werden gehen","ihr werdet gehen","sie werden gehen"],
    "Konditional":   ["ich würde gehen","du würdest gehen","er/sie würde gehen","wir würden gehen","ihr würdet gehen","sie würden gehen"],
  },
  "ex": {
    ("Präsens",0): ("Voy al supermercado.","Ich gehe zum Supermarkt."),
    ("Präsens",1): ("¿A dónde vas tan rápido?","Wohin gehst du so schnell?"),
    ("Präsens",2): ("El tren va a Barcelona.","Der Zug fährt nach Barcelona."),
    ("Präsens",3): ("Vamos a la playa hoy.","Wir gehen heute an den Strand."),
    ("Präsens",4): ("¿A dónde vais este verano?","Wohin fahrt ihr diesen Sommer?"),
    ("Präsens",5): ("Van al cine esta noche.","Sie gehen heute Abend ins Kino."),
    ("Vergangenheit",0): ("Fui a la tienda esta mañana.","Ich bin heute Morgen in den Laden gegangen."),
    ("Vergangenheit",1): ("¿Fuiste al dentista ayer?","Bist du gestern zum Zahnarzt gegangen?"),
    ("Vergangenheit",2): ("Fue a Madrid por trabajo.","Er/sie fuhr beruflich nach Madrid."),
    ("Vergangenheit",3): ("Fuimos de vacaciones a Italia.","Wir fuhren in den Urlaub nach Italien."),
    ("Vergangenheit",4): ("¿Fuisteis al partido de fútbol?","Seid ihr zum Fußballspiel gegangen?"),
    ("Vergangenheit",5): ("Fueron al concierto juntos.","Sie gingen zusammen zum Konzert."),
    ("Zukunft",0): ("Iré a la playa mañana.","Ich werde morgen an den Strand gehen."),
    ("Zukunft",1): ("¿Irás a la fiesta el sábado?","Wirst du am Samstag zur Party gehen?"),
    ("Zukunft",2): ("El jefe irá a la reunión.","Der Chef wird zum Meeting gehen."),
    ("Zukunft",3): ("Iremos juntos al aeropuerto.","Wir werden zusammen zum Flughafen gehen."),
    ("Zukunft",4): ("¿Iréis de viaje este año?","Werdet ihr dieses Jahr verreisen?"),
    ("Zukunft",5): ("Todos irán a la boda.","Alle werden zur Hochzeit gehen."),
    ("Konditional",0): ("Iría contigo, pero estoy ocupado.","Ich würde mit dir gehen, aber ich bin beschäftigt."),
    ("Konditional",1): ("¿Irías tú solo a ese lugar?","Würdest du alleine an diesen Ort gehen?"),
    ("Konditional",2): ("Iría si pudiera.","Er/sie würde gehen, wenn er/sie könnte."),
    ("Konditional",3): ("Iríamos de vacaciones a Japón.","Wir würden nach Japan in den Urlaub gehen."),
    ("Konditional",4): ("¿Iríais vosotros sin nosotros?","Würdet ihr ohne uns gehen?"),
    ("Konditional",5): ("Irían al extranjero si tuvieran dinero.","Sie würden ins Ausland gehen, wenn sie Geld hätten."),
  },
},
"hacer": {
  "start": 3069, "name": "Hacer – Konjugation", "icon": "🔨",
  "desc": "hacer in Präsens, Vergangenheit, Zukunft & Konditional",
  "conj": {
    "Präsens":       ["hago","haces","hace","hacemos","hacéis","hacen"],
    "Vergangenheit": ["hice","hiciste","hizo","hicimos","hicisteis","hicieron"],
    "Zukunft":       ["haré","harás","hará","haremos","haréis","harán"],
    "Konditional":   ["haría","harías","haría","haríamos","haríais","harían"],
  },
  "de": {
    "Präsens":       ["ich mache","du machst","er/sie macht","wir machen","ihr macht","sie machen"],
    "Vergangenheit": ["ich machte","du machtest","er/sie machte","wir machten","ihr machtet","sie machten"],
    "Zukunft":       ["ich werde machen","du wirst machen","er/sie wird machen","wir werden machen","ihr werdet machen","sie werden machen"],
    "Konditional":   ["ich würde machen","du würdest machen","er/sie würde machen","wir würden machen","ihr würdet machen","sie würden machen"],
  },
  "ex": {
    ("Präsens",0): ("Hago deporte todos los días.","Ich treibe jeden Tag Sport."),
    ("Präsens",1): ("¿Qué haces el fin de semana?","Was machst du am Wochenende?"),
    ("Präsens",2): ("Hace calor hoy.","Heute ist es warm."),
    ("Präsens",3): ("Hacemos una pausa ahora.","Wir machen jetzt eine Pause."),
    ("Präsens",4): ("¿Qué hacéis aquí?","Was macht ihr hier?"),
    ("Präsens",5): ("Los vecinos hacen demasiado ruido.","Die Nachbarn machen zu viel Lärm."),
    ("Vergangenheit",0): ("Hice los deberes ayer.","Ich habe gestern die Hausaufgaben gemacht."),
    ("Vergangenheit",1): ("¿Qué hiciste el fin de semana?","Was hast du am Wochenende gemacht?"),
    ("Vergangenheit",2): ("Hizo mucho frío ayer.","Gestern war es sehr kalt."),
    ("Vergangenheit",3): ("Hicimos una excursión juntos.","Wir haben gemeinsam einen Ausflug gemacht."),
    ("Vergangenheit",4): ("¿Hicisteis los deberes?","Habt ihr die Hausaufgaben gemacht?"),
    ("Vergangenheit",5): ("Hicieron un buen trabajo.","Sie haben gute Arbeit geleistet."),
    ("Zukunft",0): ("Haré la compra mañana.","Ich werde morgen einkaufen."),
    ("Zukunft",1): ("¿Qué harás este verano?","Was wirst du diesen Sommer machen?"),
    ("Zukunft",2): ("Mañana hará buen tiempo.","Morgen wird das Wetter schön sein."),
    ("Zukunft",3): ("Haremos lo posible.","Wir werden unser Möglichstes tun."),
    ("Zukunft",4): ("¿Qué haréis el próximo año?","Was werdet ihr nächstes Jahr machen?"),
    ("Zukunft",5): ("Harán los cambios necesarios.","Sie werden die notwendigen Änderungen vornehmen."),
    ("Konditional",0): ("Haría lo mismo en tu lugar.","Ich würde dasselbe an deiner Stelle tun."),
    ("Konditional",1): ("¿Qué harías tú en esa situación?","Was würdest du in dieser Situation tun?"),
    ("Konditional",2): ("¿Qué haría sin tu ayuda?","Was würde er/sie ohne deine Hilfe tun?"),
    ("Konditional",3): ("Haríamos más si tuviéramos tiempo.","Wir würden mehr tun, wenn wir Zeit hätten."),
    ("Konditional",4): ("¿Haríais algo diferente?","Würdet ihr etwas anderes tun?"),
    ("Konditional",5): ("Harían lo que pudieran.","Sie würden tun, was sie könnten."),
  },
},
"poder": {
  "start": 3093, "name": "Poder – Konjugation", "icon": "⚡",
  "desc": "poder in Präsens, Vergangenheit, Zukunft & Konditional",
  "conj": {
    "Präsens":       ["puedo","puedes","puede","podemos","podéis","pueden"],
    "Vergangenheit": ["pude","pudiste","pudo","pudimos","pudisteis","pudieron"],
    "Zukunft":       ["podré","podrás","podrá","podremos","podréis","podrán"],
    "Konditional":   ["podría","podrías","podría","podríamos","podríais","podrían"],
  },
  "de": {
    "Präsens":       ["ich kann","du kannst","er/sie kann","wir können","ihr könnt","sie können"],
    "Vergangenheit": ["ich konnte","du konntest","er/sie konnte","wir konnten","ihr konntet","sie konnten"],
    "Zukunft":       ["ich werde können","du wirst können","er/sie wird können","wir werden können","ihr werdet können","sie werden können"],
    "Konditional":   ["ich könnte","du könntest","er/sie könnte","wir könnten","ihr könntet","sie könnten"],
  },
  "ex": {
    ("Präsens",0): ("No puedo dormir bien.","Ich kann nicht gut schlafen."),
    ("Präsens",1): ("¿Puedes ayudarme?","Kannst du mir helfen?"),
    ("Präsens",2): ("No puede venir hoy.","Er/sie kann heute nicht kommen."),
    ("Präsens",3): ("¿Podemos entrar?","Können wir reinkommen?"),
    ("Präsens",4): ("¿Podéis hablar más alto?","Könnt ihr lauter sprechen?"),
    ("Präsens",5): ("Pueden elegir lo que quieran.","Sie können wählen, was sie möchten."),
    ("Vergangenheit",0): ("No pude terminar a tiempo.","Ich konnte nicht rechtzeitig fertig werden."),
    ("Vergangenheit",1): ("¿Pudiste dormir bien anoche?","Konntest du gestern Nacht gut schlafen?"),
    ("Vergangenheit",2): ("No pudo abrir la puerta.","Er/sie konnte die Tür nicht öffnen."),
    ("Vergangenheit",3): ("Por fin pudimos hablar.","Endlich konnten wir reden."),
    ("Vergangenheit",4): ("¿Pudisteis encontrar el hotel?","Konntet ihr das Hotel finden?"),
    ("Vergangenheit",5): ("No pudieron llegar a tiempo.","Sie konnten nicht rechtzeitig ankommen."),
    ("Zukunft",0): ("Podré ayudarte mañana.","Ich werde dir morgen helfen können."),
    ("Zukunft",1): ("Podrás hacerlo solo.","Du wirst es alleine können."),
    ("Zukunft",2): ("Podrá venir la próxima semana.","Er/sie wird nächste Woche kommen können."),
    ("Zukunft",3): ("Podremos salir más tarde.","Wir werden später ausgehen können."),
    ("Zukunft",4): ("Podréis elegir el destino.","Ihr werdet das Ziel wählen können."),
    ("Zukunft",5): ("Podrán entrar a las diez.","Sie werden um zehn reinkommen können."),
    ("Konditional",0): ("¿Podría hablar con usted?","Könnte ich mit Ihnen sprechen?"),
    ("Konditional",1): ("¿Podrías explicarme eso?","Könntest du mir das erklären?"),
    ("Konditional",2): ("Podría ser peor.","Es könnte schlimmer sein."),
    ("Konditional",3): ("Podríamos quedar mañana.","Wir könnten uns morgen treffen."),
    ("Konditional",4): ("¿Podríais ayudarnos?","Könntet ihr uns helfen?"),
    ("Konditional",5): ("Podrían llamar antes de venir.","Sie könnten vor dem Kommen anrufen."),
  },
},
"decir": {
  "start": 3117, "name": "Decir – Konjugation", "icon": "💬",
  "desc": "decir in Präsens, Vergangenheit, Zukunft & Konditional",
  "conj": {
    "Präsens":       ["digo","dices","dice","decimos","decís","dicen"],
    "Vergangenheit": ["dije","dijiste","dijo","dijimos","dijisteis","dijeron"],
    "Zukunft":       ["diré","dirás","dirá","diremos","diréis","dirán"],
    "Konditional":   ["diría","dirías","diría","diríamos","diríais","dirían"],
  },
  "de": {
    "Präsens":       ["ich sage","du sagst","er/sie sagt","wir sagen","ihr sagt","sie sagen"],
    "Vergangenheit": ["ich sagte","du sagtest","er/sie sagte","wir sagten","ihr sagtet","sie sagten"],
    "Zukunft":       ["ich werde sagen","du wirst sagen","er/sie wird sagen","wir werden sagen","ihr werdet sagen","sie werden sagen"],
    "Konditional":   ["ich würde sagen","du würdest sagen","er/sie würde sagen","wir würden sagen","ihr würdet sagen","sie würden sagen"],
  },
  "ex": {
    ("Präsens",0): ("Te digo la verdad.","Ich sage dir die Wahrheit."),
    ("Präsens",1): ("¿Qué dices?","Was sagst du?"),
    ("Präsens",2): ("El periódico dice que lloverá.","Die Zeitung sagt, es wird regnen."),
    ("Präsens",3): ("Decimos lo que pensamos.","Wir sagen, was wir denken."),
    ("Präsens",4): ("¿Lo decís en serio?","Meint ihr das ernst?"),
    ("Präsens",5): ("Dicen que es muy bueno.","Sie sagen, es ist sehr gut."),
    ("Vergangenheit",0): ("Te dije la verdad ayer.","Ich habe dir gestern die Wahrheit gesagt."),
    ("Vergangenheit",1): ("¿Qué dijiste exactamente?","Was hast du genau gesagt?"),
    ("Vergangenheit",2): ("Me dijo que llegaría tarde.","Er/sie sagte mir, er/sie würde spät kommen."),
    ("Vergangenheit",3): ("Les dijimos la verdad.","Wir haben ihnen die Wahrheit gesagt."),
    ("Vergangenheit",4): ("¿Qué dijisteis en la reunión?","Was habt ihr im Meeting gesagt?"),
    ("Vergangenheit",5): ("Dijeron que no podían venir.","Sie sagten, sie könnten nicht kommen."),
    ("Zukunft",0): ("Te diré un secreto.","Ich werde dir ein Geheimnis verraten."),
    ("Zukunft",1): ("Ya dirás cuándo estés listo.","Du sagst mir Bescheid, wenn du fertig bist."),
    ("Zukunft",2): ("El médico dirá el diagnóstico mañana.","Der Arzt wird morgen die Diagnose mitteilen."),
    ("Zukunft",3): ("Diremos la verdad siempre.","Wir werden immer die Wahrheit sagen."),
    ("Zukunft",4): ("¿Diréis algo en la reunión?","Werdet ihr im Meeting etwas sagen?"),
    ("Zukunft",5): ("Dirán lo que piensen.","Sie werden sagen, was sie denken."),
    ("Konditional",0): ("Yo diría que sí.","Ich würde sagen, ja."),
    ("Konditional",1): ("¿Qué dirías en esa situación?","Was würdest du in dieser Situation sagen?"),
    ("Konditional",2): ("Él diría la verdad.","Er/sie würde die Wahrheit sagen."),
    ("Konditional",3): ("Diríamos que está bien.","Wir würden sagen, es ist in Ordnung."),
    ("Konditional",4): ("¿Qué diríais si os preguntaran?","Was würdet ihr sagen, wenn man euch fragen würde?"),
    ("Konditional",5): ("Dirían que no hay problema.","Sie würden sagen, es gibt kein Problem."),
  },
},
"ver": {
  "start": 3141, "name": "Ver – Konjugation", "icon": "👁️",
  "desc": "ver in Präsens, Vergangenheit, Zukunft & Konditional",
  "conj": {
    "Präsens":       ["veo","ves","ve","vemos","veis","ven"],
    "Vergangenheit": ["vi","viste","vio","vimos","visteis","vieron"],
    "Zukunft":       ["veré","verás","verá","veremos","veréis","verán"],
    "Konditional":   ["vería","verías","vería","veríamos","veríais","verían"],
  },
  "de": {
    "Präsens":       ["ich sehe","du siehst","er/sie sieht","wir sehen","ihr seht","sie sehen"],
    "Vergangenheit": ["ich sah","du sahst","er/sie sah","wir sahen","ihr saht","sie sahen"],
    "Zukunft":       ["ich werde sehen","du wirst sehen","er/sie wird sehen","wir werden sehen","ihr werdet sehen","sie werden sehen"],
    "Konditional":   ["ich würde sehen","du würdest sehen","er/sie würde sehen","wir würden sehen","ihr würdet sehen","sie würden sehen"],
  },
  "ex": {
    ("Präsens",0): ("No veo nada sin mis gafas.","Ich sehe nichts ohne meine Brille."),
    ("Präsens",1): ("¿Ves ese edificio allí?","Siehst du dieses Gebäude dort?"),
    ("Präsens",2): ("Ve muy mal sin las gafas.","Er/sie sieht ohne Brille sehr schlecht."),
    ("Präsens",3): ("No nos vemos muy seguido.","Wir sehen uns nicht sehr oft."),
    ("Präsens",4): ("¿Veis la diferencia?","Seht ihr den Unterschied?"),
    ("Präsens",5): ("Se ven muy cansados.","Sie sehen sehr müde aus."),
    ("Vergangenheit",0): ("Vi una película anoche.","Ich habe gestern Abend einen Film gesehen."),
    ("Vergangenheit",1): ("¿Viste el partido?","Hast du das Spiel gesehen?"),
    ("Vergangenheit",2): ("Vio el accidente desde la ventana.","Er/sie sah den Unfall vom Fenster aus."),
    ("Vergangenheit",3): ("Vimos un arco iris.","Wir haben einen Regenbogen gesehen."),
    ("Vergangenheit",4): ("¿Visteis las noticias?","Habt ihr die Nachrichten gesehen?"),
    ("Vergangenheit",5): ("Vieron la aurora boreal.","Sie sahen das Nordlicht."),
    ("Zukunft",0): ("Veré ese filme esta noche.","Ich werde diesen Film heute Abend sehen."),
    ("Zukunft",1): ("Ya verás que todo va bien.","Du wirst sehen, dass alles gut wird."),
    ("Zukunft",2): ("Verá los resultados mañana.","Er/sie wird die Ergebnisse morgen sehen."),
    ("Zukunft",3): ("Veremos qué pasa.","Wir werden sehen, was passiert."),
    ("Zukunft",4): ("Veréis cuánto ha cambiado.","Ihr werdet sehen, wie viel sich verändert hat."),
    ("Zukunft",5): ("Verán la diferencia muy pronto.","Sie werden den Unterschied sehr bald sehen."),
    ("Konditional",0): ("Vería esa película con gusto.","Ich würde diesen Film gerne sehen."),
    ("Konditional",1): ("¿Verías esa película tú?","Würdest du diesen Film sehen?"),
    ("Konditional",2): ("Él vería antes de decidir.","Er/sie würde erst schauen, bevor er/sie entscheidet."),
    ("Konditional",3): ("Veríamos mejor desde ahí.","Von dort würden wir besser sehen."),
    ("Konditional",4): ("¿Veríais la final con nosotros?","Würdet ihr das Finale mit uns sehen?"),
    ("Konditional",5): ("Verían el problema si miraran.","Sie würden das Problem sehen, wenn sie schauten."),
  },
},
"dar": {
  "start": 3165, "name": "Dar – Konjugation", "icon": "🎁",
  "desc": "dar in Präsens, Vergangenheit, Zukunft & Konditional",
  "conj": {
    "Präsens":       ["doy","das","da","damos","dais","dan"],
    "Vergangenheit": ["di","diste","dio","dimos","disteis","dieron"],
    "Zukunft":       ["daré","darás","dará","daremos","daréis","darán"],
    "Konditional":   ["daría","darías","daría","daríamos","daríais","darían"],
  },
  "de": {
    "Präsens":       ["ich gebe","du gibst","er/sie gibt","wir geben","ihr gebt","sie geben"],
    "Vergangenheit": ["ich gab","du gabst","er/sie gab","wir gaben","ihr gabt","sie gaben"],
    "Zukunft":       ["ich werde geben","du wirst geben","er/sie wird geben","wir werden geben","ihr werdet geben","sie werden geben"],
    "Konditional":   ["ich würde geben","du würdest geben","er/sie würde geben","wir würden geben","ihr würdet geben","sie würden geben"],
  },
  "ex": {
    ("Präsens",0): ("Te doy mi número de teléfono.","Ich gebe dir meine Telefonnummer."),
    ("Präsens",1): ("¿Me das un poco de agua?","Gibst du mir etwas Wasser?"),
    ("Präsens",2): ("Da igual, no importa.","Es ist egal, das macht nichts."),
    ("Präsens",3): ("Damos una vuelta por el parque.","Wir drehen eine Runde durch den Park."),
    ("Präsens",4): ("¿Dais clases de español?","Gebt ihr Spanischunterricht?"),
    ("Präsens",5): ("Dan las gracias siempre.","Sie bedanken sich immer."),
    ("Vergangenheit",0): ("Le di el libro ayer.","Ich habe ihm/ihr gestern das Buch gegeben."),
    ("Vergangenheit",1): ("Me diste una buena idea.","Du hast mir eine gute Idee gegeben."),
    ("Vergangenheit",2): ("Me dio su número de teléfono.","Er/sie gab mir seine/ihre Telefonnummer."),
    ("Vergangenheit",3): ("Dimos una caminata de dos horas.","Wir machten einen zweistündigen Spaziergang."),
    ("Vergangenheit",4): ("¿Disteis las gracias?","Habt ihr euch bedankt?"),
    ("Vergangenheit",5): ("Dieron un concierto increíble.","Sie gaben ein unglaubliches Konzert."),
    ("Zukunft",0): ("Te daré la respuesta mañana.","Ich werde dir morgen die Antwort geben."),
    ("Zukunft",1): ("¿Darás una conferencia?","Wirst du einen Vortrag halten?"),
    ("Zukunft",2): ("El médico dará el diagnóstico.","Der Arzt wird die Diagnose mitteilen."),
    ("Zukunft",3): ("Daremos una fiesta el sábado.","Wir werden am Samstag eine Party geben."),
    ("Zukunft",4): ("¿Daréis una respuesta pronto?","Werdet ihr bald eine Antwort geben?"),
    ("Zukunft",5): ("Darán los resultados esta tarde.","Sie werden die Ergebnisse heute Nachmittag geben."),
    ("Konditional",0): ("Te daría todo lo que necesitas.","Ich würde dir alles geben, was du brauchst."),
    ("Konditional",1): ("¿Darías una segunda oportunidad?","Würdest du eine zweite Chance geben?"),
    ("Konditional",2): ("Daría cualquier cosa por estar allí.","Er/sie würde alles geben, um dort zu sein."),
    ("Konditional",3): ("Daríamos más tiempo si pudiéramos.","Wir würden mehr Zeit geben, wenn wir könnten."),
    ("Konditional",4): ("¿Daríais vuestra opinión?","Würdet ihr eure Meinung geben?"),
    ("Konditional",5): ("Darían lo mejor de sí.","Sie würden ihr Bestes geben."),
  },
},
"saber": {
  "start": 3189, "name": "Saber – Konjugation", "icon": "🧠",
  "desc": "saber in Präsens, Vergangenheit, Zukunft & Konditional",
  "conj": {
    "Präsens":       ["sé","sabes","sabe","sabemos","sabéis","saben"],
    "Vergangenheit": ["supe","supiste","supo","supimos","supisteis","supieron"],
    "Zukunft":       ["sabré","sabrás","sabrá","sabremos","sabréis","sabrán"],
    "Konditional":   ["sabría","sabrías","sabría","sabríamos","sabríais","sabrían"],
  },
  "de": {
    "Präsens":       ["ich weiß / ich kann","du weißt / du kannst","er/sie weiß","wir wissen","ihr wisst","sie wissen"],
    "Vergangenheit": ["ich wusste","du wusstest","er/sie wusste","wir wussten","ihr wusstet","sie wussten"],
    "Zukunft":       ["ich werde wissen","du wirst wissen","er/sie wird wissen","wir werden wissen","ihr werdet wissen","sie werden wissen"],
    "Konditional":   ["ich würde wissen","du würdest wissen","er/sie würde wissen","wir würden wissen","ihr würdet wissen","sie würden wissen"],
  },
  "ex": {
    ("Präsens",0): ("Sé hablar tres idiomas.","Ich kann drei Sprachen sprechen."),
    ("Präsens",1): ("¿Sabes dónde está la calle?","Weißt du, wo die Straße ist?"),
    ("Präsens",2): ("No sabe nada de eso.","Er/sie weiß nichts davon."),
    ("Präsens",3): ("Sabemos lo que hay que hacer.","Wir wissen, was zu tun ist."),
    ("Präsens",4): ("¿Sabéis cocinar bien?","Könnt ihr gut kochen?"),
    ("Präsens",5): ("Saben mucho de historia.","Sie wissen viel über Geschichte."),
    ("Vergangenheit",0): ("Supe la noticia por la radio.","Ich erfuhr die Neuigkeit im Radio."),
    ("Vergangenheit",1): ("¿Cuándo supiste la verdad?","Wann hast du die Wahrheit erfahren?"),
    ("Vergangenheit",2): ("Supo la noticia al llegar.","Er/sie erfuhr die Neuigkeit bei der Ankunft."),
    ("Vergangenheit",3): ("Supimos el resultado tarde.","Wir erfuhren das Ergebnis spät."),
    ("Vergangenheit",4): ("¿Supisteis quién ganó?","Habt ihr erfahren, wer gewonnen hat?"),
    ("Vergangenheit",5): ("No supieron qué decir.","Sie wussten nicht, was sie sagen sollten."),
    ("Zukunft",0): ("Sabré los resultados mañana.","Ich werde die Ergebnisse morgen wissen."),
    ("Zukunft",1): ("Sabrás la respuesta pronto.","Du wirst die Antwort bald wissen."),
    ("Zukunft",2): ("El juez sabrá la verdad.","Der Richter wird die Wahrheit wissen."),
    ("Zukunft",3): ("Sabremos qué decir cuando llegue.","Wir werden wissen, was zu sagen ist, wenn er kommt."),
    ("Zukunft",4): ("Sabréis los resultados mañana.","Ihr werdet die Ergebnisse morgen wissen."),
    ("Zukunft",5): ("Sabrán la noticia muy pronto.","Sie werden die Nachricht sehr bald wissen."),
    ("Konditional",0): ("Sabría qué hacer en tu lugar.","Ich würde wissen, was ich an deiner Stelle tun würde."),
    ("Konditional",1): ("¿Sabrías cómo llegar?","Würdest du wissen, wie man hinkommt?"),
    ("Konditional",2): ("Él sabría la solución.","Er/sie würde die Lösung wissen."),
    ("Konditional",3): ("Sabríamos qué hacer.","Wir würden wissen, was zu tun ist."),
    ("Konditional",4): ("¿Sabríais arreglarlo?","Würdet ihr wissen, wie man es repariert?"),
    ("Konditional",5): ("Sabrían cómo resolver el problema.","Sie würden wissen, wie man das Problem löst."),
  },
},
"querer": {
  "start": 3213, "name": "Querer – Konjugation", "icon": "❤️",
  "desc": "querer in Präsens, Vergangenheit, Zukunft & Konditional",
  "conj": {
    "Präsens":       ["quiero","quieres","quiere","queremos","queréis","quieren"],
    "Vergangenheit": ["quise","quisiste","quiso","quisimos","quisisteis","quisieron"],
    "Zukunft":       ["querré","querrás","querrá","querremos","querréis","querrán"],
    "Konditional":   ["querría","querrías","querría","querríamos","querríais","querrían"],
  },
  "de": {
    "Präsens":       ["ich will / ich möchte","du willst / du möchtest","er/sie will","wir wollen","ihr wollt","sie wollen"],
    "Vergangenheit": ["ich wollte","du wolltest","er/sie wollte","wir wollten","ihr wolltet","sie wollten"],
    "Zukunft":       ["ich werde wollen","du wirst wollen","er/sie wird wollen","wir werden wollen","ihr werdet wollen","sie werden wollen"],
    "Konditional":   ["ich würde wollen / ich möchte","du würdest wollen","er/sie würde wollen","wir würden wollen","ihr würdet wollen","sie würden wollen"],
  },
  "ex": {
    ("Präsens",0): ("Quiero un café, por favor.","Ich möchte einen Kaffee, bitte."),
    ("Präsens",1): ("¿Qué quieres comer?","Was möchtest du essen?"),
    ("Präsens",2): ("Quiere aprender español.","Er/sie möchte Spanisch lernen."),
    ("Präsens",3): ("Queremos viajar a México.","Wir möchten nach Mexiko reisen."),
    ("Präsens",4): ("¿Qué queréis de postre?","Was möchtet ihr als Nachtisch?"),
    ("Präsens",5): ("Quieren salir esta noche.","Sie möchten heute Abend ausgehen."),
    ("Vergangenheit",0): ("Quise llamarte pero no pude.","Ich wollte dich anrufen, aber ich konnte nicht."),
    ("Vergangenheit",1): ("¿Por qué no quisiste venir?","Warum wolltest du nicht kommen?"),
    ("Vergangenheit",2): ("No quiso escuchar.","Er/sie wollte nicht zuhören."),
    ("Vergangenheit",3): ("No quisimos molestar.","Wir wollten nicht stören."),
    ("Vergangenheit",4): ("¿Quisisteis quedaros más tiempo?","Wolltet ihr länger bleiben?"),
    ("Vergangenheit",5): ("No quisieron esperar más.","Sie wollten nicht länger warten."),
    ("Zukunft",0): ("Siempre querré lo mejor para ti.","Ich werde immer das Beste für dich wollen."),
    ("Zukunft",1): ("Ya verás que querrás volver.","Du wirst sehen, dass du zurückkommen möchtest."),
    ("Zukunft",2): ("Él querrá saber la verdad.","Er/sie wird die Wahrheit wissen wollen."),
    ("Zukunft",3): ("Querremos saber el resultado.","Wir werden das Ergebnis wissen wollen."),
    ("Zukunft",4): ("¿Querréis venir con nosotros?","Werdet ihr mit uns kommen wollen?"),
    ("Zukunft",5): ("Querrán participar también.","Sie werden auch teilnehmen wollen."),
    ("Konditional",0): ("Querría ir, pero no puedo.","Ich würde gerne gehen, aber ich kann nicht."),
    ("Konditional",1): ("¿Querrías probar la comida?","Würdest du das Essen probieren wollen?"),
    ("Konditional",2): ("Querría saber más sobre eso.","Er/sie würde mehr darüber wissen wollen."),
    ("Konditional",3): ("Querríamos que vinieras.","Wir würden möchten, dass du kommst."),
    ("Konditional",4): ("¿Querríais un café?","Würdet ihr einen Kaffee möchten?"),
    ("Konditional",5): ("Querrían volver a visitarnos.","Sie würden uns gerne wieder besuchen."),
  },
},
"venir": {
  "start": 3237, "name": "Venir – Konjugation", "icon": "🏃",
  "desc": "venir in Präsens, Vergangenheit, Zukunft & Konditional",
  "conj": {
    "Präsens":       ["vengo","vienes","viene","venimos","venís","vienen"],
    "Vergangenheit": ["vine","viniste","vino","vinimos","vinisteis","vinieron"],
    "Zukunft":       ["vendré","vendrás","vendrá","vendremos","vendréis","vendrán"],
    "Konditional":   ["vendría","vendrías","vendría","vendríamos","vendríais","vendrían"],
  },
  "de": {
    "Präsens":       ["ich komme","du kommst","er/sie kommt","wir kommen","ihr kommt","sie kommen"],
    "Vergangenheit": ["ich kam","du kamst","er/sie kam","wir kamen","ihr kamt","sie kamen"],
    "Zukunft":       ["ich werde kommen","du wirst kommen","er/sie wird kommen","wir werden kommen","ihr werdet kommen","sie werden kommen"],
    "Konditional":   ["ich würde kommen","du würdest kommen","er/sie würde kommen","wir würden kommen","ihr würdet kommen","sie würden kommen"],
  },
  "ex": {
    ("Präsens",0): ("Vengo del trabajo ahora.","Ich komme gerade von der Arbeit."),
    ("Präsens",1): ("¿Vienes con nosotros?","Kommst du mit uns?"),
    ("Präsens",2): ("El tren viene con retraso.","Der Zug kommt mit Verspätung."),
    ("Präsens",3): ("Venimos de España.","Wir kommen aus Spanien."),
    ("Präsens",4): ("¿De dónde venís?","Woher kommt ihr?"),
    ("Präsens",5): ("Mis padres vienen de visita.","Meine Eltern kommen zu Besuch."),
    ("Vergangenheit",0): ("Vine en tren desde Madrid.","Ich kam mit dem Zug aus Madrid."),
    ("Vergangenheit",1): ("¿Cuándo viniste a Alemania?","Wann bist du nach Deutschland gekommen?"),
    ("Vergangenheit",2): ("Vino sin avisar.","Er/sie kam ohne Vorankündigung."),
    ("Vergangenheit",3): ("Vinimos juntos desde el aeropuerto.","Wir kamen gemeinsam vom Flughafen."),
    ("Vergangenheit",4): ("¿Por qué vinisteis tan tarde?","Warum seid ihr so spät gekommen?"),
    ("Vergangenheit",5): ("Vinieron todos a la boda.","Sie kamen alle zur Hochzeit."),
    ("Zukunft",0): ("Vendré a recogerte al aeropuerto.","Ich werde dich am Flughafen abholen."),
    ("Zukunft",1): ("¿Vendrás a la fiesta?","Wirst du zur Party kommen?"),
    ("Zukunft",2): ("Mi jefe vendrá mañana.","Mein Chef wird morgen kommen."),
    ("Zukunft",3): ("Vendremos en coche.","Wir werden mit dem Auto kommen."),
    ("Zukunft",4): ("¿Vendréis todos?","Werdet ihr alle kommen?"),
    ("Zukunft",5): ("Vendrán muchos invitados.","Viele Gäste werden kommen."),
    ("Konditional",0): ("Vendría contigo si pudiera.","Ich würde mit dir kommen, wenn ich könnte."),
    ("Konditional",1): ("¿Vendrías a visitarnos?","Würdest du uns besuchen kommen?"),
    ("Konditional",2): ("Vendría antes si supiera.","Er/sie würde früher kommen, wenn er/sie es wüsste."),
    ("Konditional",3): ("Vendríamos en tren.","Wir würden mit dem Zug kommen."),
    ("Konditional",4): ("¿Vendríais a la cena?","Würdet ihr zum Abendessen kommen?"),
    ("Konditional",5): ("Vendrían todos si los invitaras.","Sie würden alle kommen, wenn du sie einladen würdest."),
  },
},
"poner": {
  "start": 3261, "name": "Poner – Konjugation", "icon": "📌",
  "desc": "poner in Präsens, Vergangenheit, Zukunft & Konditional",
  "conj": {
    "Präsens":       ["pongo","pones","pone","ponemos","ponéis","ponen"],
    "Vergangenheit": ["puse","pusiste","puso","pusimos","pusisteis","pusieron"],
    "Zukunft":       ["pondré","pondrás","pondrá","pondremos","pondréis","pondrán"],
    "Konditional":   ["pondría","pondrías","pondría","pondríamos","pondríais","pondrían"],
  },
  "de": {
    "Präsens":       ["ich lege / stelle","du legst / stellst","er/sie legt","wir legen","ihr legt","sie legen"],
    "Vergangenheit": ["ich legte","du legtest","er/sie legte","wir legten","ihr legtet","sie legten"],
    "Zukunft":       ["ich werde legen","du wirst legen","er/sie wird legen","wir werden legen","ihr werdet legen","sie werden legen"],
    "Konditional":   ["ich würde legen","du würdest legen","er/sie würde legen","wir würden legen","ihr würdet legen","sie würden legen"],
  },
  "ex": {
    ("Präsens",0): ("Pongo la mesa cada día.","Ich decke jeden Tag den Tisch."),
    ("Präsens",1): ("¿Dónde pones las llaves?","Wohin legst du die Schlüssel?"),
    ("Präsens",2): ("Pone mucho esfuerzo en su trabajo.","Er/sie gibt viel Mühe in seine/ihre Arbeit."),
    ("Präsens",3): ("Ponemos música mientras comemos.","Wir machen Musik an, während wir essen."),
    ("Präsens",4): ("¿Dónde ponéis las maletas?","Wohin stellt ihr die Koffer?"),
    ("Präsens",5): ("Ponen el telediario a las nueve.","Sie schalten um neun die Nachrichten ein."),
    ("Vergangenheit",0): ("Puse el libro en la estantería.","Ich stellte das Buch ins Regal."),
    ("Vergangenheit",1): ("¿Dónde pusiste mi móvil?","Wo hast du mein Handy hingelegt?"),
    ("Vergangenheit",2): ("Puso la mano en el fuego.","Er/sie legte die Hand ins Feuer."),
    ("Vergangenheit",3): ("Pusimos la mesa juntos.","Wir haben zusammen den Tisch gedeckt."),
    ("Vergangenheit",4): ("¿Dónde pusisteis las compras?","Wo habt ihr die Einkäufe hingestellt?"),
    ("Vergangenheit",5): ("Pusieron el árbol de Navidad.","Sie haben den Weihnachtsbaum aufgestellt."),
    ("Zukunft",0): ("Pondré la lavadora esta noche.","Ich werde heute Abend die Waschmaschine anmachen."),
    ("Zukunft",1): ("¿Dónde pondrás el sofá?","Wohin wirst du das Sofa stellen?"),
    ("Zukunft",2): ("El profesor pondrá el examen mañana.","Der Lehrer wird morgen die Prüfung geben."),
    ("Zukunft",3): ("Pondremos las reglas claras.","Wir werden die Regeln klar festlegen."),
    ("Zukunft",4): ("¿Dónde pondréis la cama?","Wohin werdet ihr das Bett stellen?"),
    ("Zukunft",5): ("Pondrán el anuncio en el periódico.","Sie werden die Anzeige in die Zeitung setzen."),
    ("Konditional",0): ("Yo pondría las flores aquí.","Ich würde die Blumen hier hinstellen."),
    ("Konditional",1): ("¿Dónde pondrías el cuadro?","Wo würdest du das Bild hinhängen?"),
    ("Konditional",2): ("Él pondría más sal.","Er/sie würde mehr Salz hinzufügen."),
    ("Konditional",3): ("Pondríamos la tele en otro sitio.","Wir würden den Fernseher woanders hinstellen."),
    ("Konditional",4): ("¿Pondríais la mesa?","Würdet ihr den Tisch decken?"),
    ("Konditional",5): ("Lo pondrían todo en orden.","Sie würden alles in Ordnung bringen."),
  },
},
"salir": {
  "start": 3285, "name": "Salir – Konjugation", "icon": "🚪",
  "desc": "salir in Präsens, Vergangenheit, Zukunft & Konditional",
  "conj": {
    "Präsens":       ["salgo","sales","sale","salimos","salís","salen"],
    "Vergangenheit": ["salí","saliste","salió","salimos","salisteis","salieron"],
    "Zukunft":       ["saldré","saldrás","saldrá","saldremos","saldréis","saldrán"],
    "Konditional":   ["saldría","saldrías","saldría","saldríamos","saldríais","saldrían"],
  },
  "de": {
    "Präsens":       ["ich gehe (weg)","du gehst (weg)","er/sie geht (weg)","wir gehen (weg)","ihr geht (weg)","sie gehen (weg)"],
    "Vergangenheit": ["ich ging (weg)","du gingst (weg)","er/sie ging (weg)","wir gingen (weg)","ihr gingt (weg)","sie gingen (weg)"],
    "Zukunft":       ["ich werde ausgehen","du wirst ausgehen","er/sie wird ausgehen","wir werden ausgehen","ihr werdet ausgehen","sie werden ausgehen"],
    "Konditional":   ["ich würde ausgehen","du würdest ausgehen","er/sie würde ausgehen","wir würden ausgehen","ihr würdet ausgehen","sie würden ausgehen"],
  },
  "ex": {
    ("Präsens",0): ("Salgo de casa a las ocho.","Ich gehe um acht von zu Hause weg."),
    ("Präsens",1): ("¿A qué hora sales del trabajo?","Um wie viel Uhr gehst du von der Arbeit?"),
    ("Präsens",2): ("El tren sale a las diez.","Der Zug fährt um zehn ab."),
    ("Präsens",3): ("Salimos a cenar los viernes.","Freitags gehen wir essen."),
    ("Präsens",4): ("¿A qué hora salís?","Um wie viel Uhr geht ihr weg?"),
    ("Präsens",5): ("Salen juntos los fines de semana.","Sie gehen am Wochenende zusammen aus."),
    ("Vergangenheit",0): ("Salí tarde de la oficina.","Ich verließ das Büro spät."),
    ("Vergangenheit",1): ("¿Cuándo saliste de casa?","Wann bist du von zu Hause weggegangen?"),
    ("Vergangenheit",2): ("El vuelo salió a tiempo.","Der Flug ist pünktlich abgeflogen."),
    ("Vergangenheit",3): ("Salimos a las ocho en punto.","Wir sind um Punkt acht losgegangen."),
    ("Vergangenheit",4): ("¿A qué hora salisteis anoche?","Um wie viel Uhr seid ihr gestern Abend losgegangen?"),
    ("Vergangenheit",5): ("Salieron de la reunión tarde.","Sie sind spät aus dem Meeting herausgekommen."),
    ("Zukunft",0): ("Saldré del trabajo a las cinco.","Ich werde um fünf Uhr von der Arbeit gehen."),
    ("Zukunft",1): ("¿A qué hora saldrás?","Um wie viel Uhr wirst du losgehen?"),
    ("Zukunft",2): ("El tren saldrá con retraso.","Der Zug wird mit Verspätung abfahren."),
    ("Zukunft",3): ("Saldremos mañana temprano.","Wir werden morgen früh aufbrechen."),
    ("Zukunft",4): ("¿A qué hora saldréis?","Um wie viel Uhr werdet ihr losfahren?"),
    ("Zukunft",5): ("Los resultados saldrán mañana.","Die Ergebnisse werden morgen herauskommen."),
    ("Konditional",0): ("Saldría antes si pudiera.","Ich würde früher weggehen, wenn ich könnte."),
    ("Konditional",1): ("¿Saldrías con ese tiempo?","Würdest du bei diesem Wetter rausgehen?"),
    ("Konditional",2): ("Saldría de vacaciones mañana mismo.","Er/sie würde sofort in den Urlaub fahren."),
    ("Konditional",3): ("Saldríamos, pero llueve.","Wir würden rausgehen, aber es regnet."),
    ("Konditional",4): ("¿Saldríais en esas condiciones?","Würdet ihr unter diesen Bedingungen losgehen?"),
    ("Konditional",5): ("Saldrían si hiciera mejor tiempo.","Sie würden rausgehen, wenn das Wetter besser wäre."),
  },
},
}  # end DATA

# ─── Generate vocab entries ──────────────────────────────────────────────────
new_entries = []
module_meta = {}  # verb -> (data, list_of_ids)

for verb in VERB_ORDER:
    v = DATA[verb]
    cur_id = v["start"]
    ids = []
    for tense in TENSE_ORDER:
        for idx, person in enumerate(PERSONS):
            entry = {
                "id": str(cur_id),
                "spanish": v["conj"][tense][idx],
                "german": v["de"][tense][idx],
                "category": f"Verben: {verb}",
                "sentence_es": v["ex"][(tense, idx)][0],
                "sentence_de": v["ex"][(tense, idx)][1],
                "note": f"{verb} – {tense} – {person}",
                "audio": "",
            }
            new_entries.append(entry)
            ids.append(str(cur_id))
            cur_id += 1
    for extra in v.get("extra", []):
        entry = {
            "id": str(cur_id),
            "spanish": extra["spanish"],
            "german": extra["german"],
            "category": f"Verben: {verb}",
            "sentence_es": extra["sentence_es"],
            "sentence_de": extra["sentence_de"],
            "note": extra["note"],
            "audio": "",
        }
        new_entries.append(entry)
        ids.append(str(cur_id))
        cur_id += 1
    module_meta[verb] = (v, ids)

print(f"Generated {len(new_entries)} vocab entries")
print(f"ID range: {new_entries[0]['id']} – {new_entries[-1]['id']}")

# ─── Append to vocabulario-es.json ──────────────────────────────────────────
vocab_path = os.path.join(BASE, "data", "vocabulario-es.json")
with open(vocab_path, encoding="utf-8") as f:
    vocab = json.load(f)

max_existing = max(int(e["id"]) for e in vocab)
print(f"Max existing ID: {max_existing}")
assert max_existing == 2947, f"Expected 2947, got {max_existing}"

vocab.extend(new_entries)
with open(vocab_path, "w", encoding="utf-8") as f:
    json.dump(vocab, f, ensure_ascii=False, indent=2)
    f.write("\n")
print(f"vocabulario-es.json: now {len(vocab)} entries")

# ─── Write 15 module files ───────────────────────────────────────────────────
modules_dir = os.path.join(BASE, "data", "modules")

for verb in VERB_ORDER:
    v, ids = module_meta[verb]
    verb_id = f"verben-{verb}"
    mod = {
        "id": verb_id,
        "name": v["name"],
        "description": v["desc"],
        "icon": v["icon"],
        "type": "vocabulary",
        "vocabIds": ids,
    }
    out = os.path.join(modules_dir, f"{verb_id}.json")
    with open(out, "w", encoding="utf-8") as f:
        json.dump(mod, f, ensure_ascii=False, indent=2)
        f.write("\n")
    print(f"  {verb_id}.json ({len(ids)} cards)")

# ─── Update index.json ───────────────────────────────────────────────────────
index_path = os.path.join(modules_dir, "index.json")
with open(index_path, encoding="utf-8") as f:
    index = json.load(f)

for verb in VERB_ORDER:
    v, ids = module_meta[verb]
    verb_id = f"verben-{verb}"
    index.append({
        "id": verb_id,
        "name": v["name"],
        "description": v["desc"],
        "icon": v["icon"],
        "type": "vocabulary",
        "file": f"{verb_id}.json",
    })

with open(index_path, "w", encoding="utf-8") as f:
    json.dump(index, f, ensure_ascii=False, indent=2)
    f.write("\n")
print(f"index.json: {len(index)} modules total")
print("All done.")
